import { createPlugin } from '../../../../MapStore2/web/client/utils/PluginsUtils';
import anuga from "./reducersAnuga";
import anugaContainer from "./components/anugaContainer";
import {
    initAnugaEpic,
    cancelAnugaRunEpic,
    retryAnugaRunEpic,
    pollActiveRunStatusEpic,
    runAnugaScenarioEpic,
    runNetworkEpic,
    saveAnugaScenarioEpic,
    saveNetworkEpic,
    pollAnugaScenarioEpic,
    deleteAnugaScenarioEpic,
    createAnugaBoundaryEpic,
    createAnugaFrictionEpic,
    createAnugaInflowEpic,
    createAnugaStructureEpic,
    createAnugaMeshRegionEpic,
    createNetworkEpic,
    createCatchmentEpic,
    createNodesEpic,
    createLinksEpic,
    createFigureEpic,
    addAnugaBoundaryEpic,
    addAnugaFrictionEpic,
    addAnugaInflowEpic,
    addAnugaStructureEpic,
    addAnugaFullMeshEpic,
    addAnugaMeshRegionEpic,
    addCatchmentEpic,
    addNodesEpic,
    addLinksEpic,
    prePopulateAnugaFeatureGridWithDefaults,
    updateComputeInstanceEpic,
    updateAnugaModelTitle,
    pollAnugaModelCreationEpic,
    compareScenarioEpic,
    pollComparisonEpic,
    addComparisonEpic,
    getAnugaResourcesEpic,
    manageTerrain3DEpic,
    ensureAnugaGroupsEpic,
    taskCompleteLayerEpic,
    anugaMapLayerGroupEpic,
    triggerFetchMyPermsOnInitEpic,
    fetchMyPermsEpic,
    deleteElevationEpic,
    deleteBoundaryEpic,
    deleteFrictionEpic,
    deleteInflowEpic
} from "./epicsAnuga";
import {
    fetchMembershipsEpic,
    addMembershipEpic,
    updateMembershipEpic,
    deleteMembershipEpic,
    updateProjectVisibilityEpic
} from "./epics/membershipEpics";

export default createPlugin('Anuga', {
    component: anugaContainer,
    reducers: {
        anuga
    },
    epics: {
        initAnugaEpic,
        cancelAnugaRunEpic,
        retryAnugaRunEpic,
        pollActiveRunStatusEpic,
        runAnugaScenarioEpic,
        runNetworkEpic,
        saveAnugaScenarioEpic,
        saveNetworkEpic,
        pollAnugaScenarioEpic,
        deleteAnugaScenarioEpic,
        createAnugaBoundaryEpic,
        createAnugaFrictionEpic,
        createAnugaInflowEpic,
        createAnugaStructureEpic,
        createAnugaMeshRegionEpic,
        createNetworkEpic,
        createCatchmentEpic,
        createNodesEpic,
        createLinksEpic,
        createFigureEpic,
        addAnugaBoundaryEpic,
        addAnugaFrictionEpic,
        addAnugaInflowEpic,
        addAnugaStructureEpic,
        addAnugaFullMeshEpic,
        addAnugaMeshRegionEpic,
        addCatchmentEpic,
        addNodesEpic,
        addLinksEpic,
        prePopulateAnugaFeatureGridWithDefaults,
        updateComputeInstanceEpic,
        updateAnugaModelTitle,
        pollAnugaModelCreationEpic,
        compareScenarioEpic,
        pollComparisonEpic,
        addComparisonEpic,
        getAnugaResourcesEpic,
        manageTerrain3DEpic,
        ensureAnugaGroupsEpic,
        taskCompleteLayerEpic,
        anugaMapLayerGroupEpic,
        fetchMembershipsEpic,
        addMembershipEpic,
        updateMembershipEpic,
        deleteMembershipEpic,
        updateProjectVisibilityEpic,
        triggerFetchMyPermsOnInitEpic,
        fetchMyPermsEpic,
        deleteElevationEpic,
        deleteBoundaryEpic,
        deleteFrictionEpic,
        deleteInflowEpic
    }
});
