import { createPlugin } from '../../../../MapStore2/web/client/utils/PluginsUtils';
import anuga from "./reducersAnuga";
import anugaContainer from "./components/anugaContainer";
import {
    initAnugaEpic,
    cancelAnugaRunEpic,
    pollAnugaElevationEpic,
    runAnugaScenarioEpic,
    runNetworkEpic,
    saveAnugaScenarioEpic,
    pollAnugaScenarioEpic,
    deleteAnugaScenarioEpic,
    createAnugaBoundaryEpic,
    createAnugaFrictionEpic,
    createAnugaInflowEpic,
    createAnugaStructureEpic,
    createAnugaMeshRegionEpic,
    createNetworkEpic,
    createCatchmentEpic,
    createNodesEpic,
    createLinksEpic,
    addAnugaBoundaryEpic,
    addAnugaFrictionEpic,
    addAnugaInflowEpic,
    addAnugaStructureEpic,
    addAnugaFullMeshEpic,
    addAnugaMeshRegionEpic,
    // addNetworkEpic,
    addCatchmentEpic,
    addNodesEpic,
    addLinksEpic,
    prePopulateAnugaFeatureGridWithDefaults,
    updateComputeInstanceEpic,
    updateAnugaModelTitle,
    pollAnugaModelCreationEpic
} from "./epicsAnuga";

export default createPlugin('Anuga', {
    component: anugaContainer,
    reducers: {
        anuga
    },
    epics: {
        initAnugaEpic,
        cancelAnugaRunEpic,
        pollAnugaElevationEpic,
        runAnugaScenarioEpic,
        runNetworkEpic,
        saveAnugaScenarioEpic,
        pollAnugaScenarioEpic,
        deleteAnugaScenarioEpic,
        createAnugaBoundaryEpic,
        createAnugaFrictionEpic,
        createAnugaInflowEpic,
        createAnugaStructureEpic,
        createAnugaMeshRegionEpic,
        createNetworkEpic,
        createCatchmentEpic,
        createNodesEpic,
        createLinksEpic,
        addAnugaBoundaryEpic,
        addAnugaFrictionEpic,
        addAnugaInflowEpic,
        addAnugaStructureEpic,
        addAnugaFullMeshEpic,
        addAnugaMeshRegionEpic,
        // addNetworkEpic,
        addCatchmentEpic,
        addNodesEpic,
        addLinksEpic,
        prePopulateAnugaFeatureGridWithDefaults,
        updateComputeInstanceEpic,
        updateAnugaModelTitle,
        pollAnugaModelCreationEpic
    }
});
